# Generated by Django 5.1.6 on 2025-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=11112, max_length=64, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
